## Crea un docker-compose.yaml que contenga los siguientes servicios:
## - Un servicio llamado "app" que ejecute el contenedor de la imagen "app" que creaste en el desafío anterior.
## - Un servicio llamado "db" que ejecute el contenedor de la imagen "db" que creaste en el desafío anterior
version: '3.8'
services:
  mongo:
    image: mongo:latest
    container_name: mongoprueba
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: