## Crea un docker-compose.yaml que contenga los siguientes servicios:
## - Un servicio llamado "app" que ejecute el contenedor de la imagen "app" que creaste en el desafío anterior.
## - Un servicio llamado "db" que ejecute el contenedor de la imagen "db" que creaste en el desafío anterior

version: '3'
services:
  app:
    container_name: node-mongo-app
    volumes:
      - .:/app
    restart: always
    build: .
    ports:
      - '3000:3000'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    restart: always 
    ports:
      - '27017:27017'