apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    io.kompose.service: app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: app
  template:
    metadata:
      labels:
        io.kompose.service: app
    spec:
      containers:
        - name: educacionit-app
          image: joselintp/educacionit-app:v1.0.0
          ports:
            - containerPort: 3000
              protocol: TCP
          env:
            - name: MONGO_DB_NAME
              value: app-desafio10
            - name: MONGO_DB_PASS
              value: Psw*7845!
            - name: MONGO_DB_URI
              value: mongodb://db-server:27017
            - name: MONGO_DB_USER
              value: root
            - name: PORT
              value: "3000"
      restartPolicy: Always