## Crea un docker-compose.yaml que contenga los siguientes servicios:
## - Un servicio llamado "app" que ejecute el contenedor de la imagen "app" que creaste en el desafío anterior.
## - Un servicio llamado "db" que ejecute el contenedor de la imagen "db" que creaste en el desafío anterior

## version: '3.8' Podemos omitir

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - MONGO_DB_URI=mongodb://mongo:27017
      - MONGO_DB_NAME=app-desafio10
      - MONGO_DB_USER=root
      - MONGO_DB_PASS=example
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: