apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "128Mi"   # Solicitud mínima de memoria
            cpu: "100m"       # Solicitud mínima de CPU
          limits:
            memory: "256Mi"   # Límite máximo de memoria
            cpu: "200m"       # Límite máximo de CPU
            