- name: Deployment de un sitio estatico
  hosts: all
  become: yes
  pre_tasks:
    - name: Verificar si el OS es Ubuntu
      set_fact:
        is_ubuntu: "{{ ansible_distribution == 'Ubuntu' }}"
  vars_files:
    - vars/vars-site.yml
  tasks:
    - include_tasks: includes/install-apache2.yml
    - include_tasks: includes/create-site-dir.yml
    - include_tasks: includes/copy-index-html.yml
    - include_tasks: includes/configure-apache.yml
    - include_tasks: includes/enable-site.yml
    - include_tasks: includes/disable-default-site.yml
    - include_tasks: includes/change-webmaster-email.yml
  handlers:
    - name: Reload Apache
      service:
        name: apache2
        state: reloaded
      when: is_ubuntu
