pipeline {
    agent any
    parameters {
        string(name: 'process_name', defaultValue: 'default_process', description: 'Nombre del proceso')
    }
    stages {
        stage('Set execution persmisions') {
            steps {
                sh 'chmod +x Clase14/main.sh'
            }
        }
        stage('Run script') {
            steps {
                sh './main.sh ${params.process_name}'
            }
        }
    }
}
