pipeline {
    agent any
    parameters {
        string(name: 'process_name', defaultValue: 'default_process', description: 'Nombre del proceso')
    }
    stages {
        stage('Set execution persmisions') {
            steps {
            // Establecer los permisos de ejecución en el archivo main.sh ubicado en la ruta ClasesBootDevops/Clase14/
                sh 'chmod +x ClasesBootDevops/Clase14/main.sh'
            }
        }
        stage('Run script') {
            steps {
                // Se ejecuta el script main.sh ubicado en la ruta ClasesBootDevops/Clase14/ y se pasa el valor del parámetro process_name como argumento al script
                sh "./ClasesBootDevops/Clase14/main.sh ${params.process_name}"
            }
        }
    }
}
